### PR TITLE
Feat : fr translation

### PR DESCRIPTION
**Pull request by alexbelgium**
Hello,

I've re-created the french translation (and english translation fix) PR while using Github online which should ensure to keep current formatting

### CODE REVIEW

**Comment by alexbelgium** [comment]
Shouldn't it be in english by default, and nl only for people who have set their HA this way ?

**Comment by alexbelgium** [comment]
I've noticed that last line of the js was modified although I didn't touch it. It looks like github automatically adds a newline at end of the file. Not sure how to avoid that.

**Comment by aex351** [comment]
Thanks for your contribution. 

The pull request focuses on adding French language. It also contains a small fix for the English language and with that fix the last line, that contains an external Javascript library also has been reported as being changed. I can't verify this has been untouched. For that reason I can't approve this pull request.

My proposed solution. Keep this pull request focused on the French language (because that's the main goal) and remove dd7cb7f. You can make another pull request for that or I will fix it myself in the upcoming update.

**Comment by alexbelgium** [comment]
>Also that fix belongs to the 'Neerslag Card' (which is in a separate repository). You can make another pull request for that or I will fix it myself in the upcoming update.

Well I have also created [a PR](https://github.com/aex351/home-assistant-neerslag-card/pull/31) on the card repo for the French translation. However I see that there is the same issue of modifying the javascript library.

I'll try a last time then will drop the PR if that doesn't work.

**Comment by aex351** [comment]
I have cherry picked the main feature of this pull request. The other commits I will include in the 'Neerslag Card' repository.

**Pull request closed without merging**
